name: 'Bikeshed'
description: 'Build Bikeshed'
inputs:
  bikeshed-version:
    description: 'version of Bikeshed to use'
    required: false
    default: 'latest'
  src:
    description: 'input .bs file(s)'
    required: false
    default: '**/*.bs'
runs:
  using: 'node12'
  main: 'dist/index.js'
